import Head from 'next/head';
import PomodoroTimer from '@/components/Pomodoro';
import { BackgroundProvider } from '@/context/BackgroundContext';

import { signIn, signOut, useSession } from 'next-auth/react';

export default function Home() {
  const { data: session } = useSession();

  const handleSignin = (e) => {
    e.preventDefault();
    signIn();
  };

  const handleSignout = (e) => {
    e.preventDefault();
    signOut();
  };

  return (
    <>
      <Head>
        <title>Pomodoro 🍅 </title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <BackgroundProvider>
        {session && <a href="#" onClick={handleSignout} className="btn-signin">Sign out</a>}
        {!session && <a href="#" onClick={handleSignin} className="btn-signin">Sign in</a>}
        <PomodoroTimer />
      </BackgroundProvider>
    </>
  );
}
