// Next
import Head from 'next/head';

// Context
import { BackgroundProvider } from '@/context/BackgroundContext';

// Components
import StatisticsComponent from '@/components/StatisticsComponent';

export default function Statistics() {
    return (
        <>
            <Head>
                <title>Statistics - Pomodoro 🍅 </title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <BackgroundProvider>
                <StatisticsComponent />
            </BackgroundProvider>
        </>
    );
}
