import Head from 'next/head';
import { BackgroundProvider } from '@/context/BackgroundContext';
import SessionStatistics from '@/components/SessionStatistics';
import ChartComponentStats from '@/components/ChartComponentStats';

export default function Statistics() {
    return (
        <>
            <Head>
                <title>Statistics - Pomodoro 🍅 </title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <BackgroundProvider>
                <div className="bg-gray-100 min-h-screen">
                    <header className="py-4 bg-white">
                        <div className="container mx-auto">
                            <h1 className="text-2xl font-bold text-gray-800">Your Statistics</h1>
                        </div>
                    </header>
                    <SessionStatistics />

                    <ChartComponentStats />
                </div>
            </BackgroundProvider>
        </>
    );
}
